services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    ports:
      - "8000:8000"
    command: bash -c "gunicorn -w 1 -b 0.0.0.0:8000 app:app && python scraper.py"
    depends_on:
      - splash
    environment:
      SPLASH_URL: "http://splash:8050"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app

  splash:
    command: ["--max-timeout", "3600"]
    image: scrapinghub/splash
    ports:
      - "8050:8050"