version: "3.8"
services:
  flask:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/flask-scrapy
    depends_on:
      - splash
    environment:
      SPLASH_URL: "http://splash:8050"
  splash:
    command: ["--max-timeout", "3600"]
    image: scrapinghub/splash
    ports:
      - "8050:8050"

